### ISSUE TITLE
Bug: No way to configure non-member messages for current site while plugin is activated.

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-network-subsite#14]
The non-member and logged out messages aren't being replaced with the settings from the main site and there is no way to configure the messages while the plugin is activated. We should probably default to the main site's settings (or maybe better) add these settings to the PMPro Multisite Membership Settings admin page.

**Support Ticket (Moderators Only)**
https://www.paidmembershipspro.com/forums/topic/multisite-login-register-wont-redirect-to-main/?skipped

**Comment by kimcoleman** [comment]
I have 2 new users reporting this same issue. We have instructed them to temporarily disable the Add On so that the Advanced Settings for these fields are editable. 

More discussion should be had to determine the best approach, whether that is to inherit the main site's content OR allow some of the settings to be editable on a per-subsite basis.
